name: scully-quantum-optics
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - nodejs
  - qutip
  - cookiecutter
  - myst-parser
  - sympy
  - mpmath
  - pytest